//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using ÖnMuhasebeProjesi.Interfaces;

namespace ÖnMuhasebeProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPO:IEntity
    {
        public int ID { get; set; }
        public string DepoKodu { get; set; }
        public string DepoAdı { get; set; }
        public string YetkiliKodu { get; set; }
        public string YetkiliAdı { get; set; }
        public string İl { get; set; }
        public string İlçe { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Açıklama { get; set; }
    }
}
